"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Types", [
      {
        name: "Normal",
        color: "0xFF919AA2",
        imgUrl: "http://localhost:3000/assets/types/normal.png",
        imgUrlOutline: "http://localhost:3000/assets/types/normalOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fire",
        color: "0xFFFF9D55",
        imgUrl: "http://localhost:3000/assets/types/fire.png",
        imgUrlOutline: "http://localhost:3000/assets/types/fireOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Water",
        color: "0xFF5090D6",
        imgUrl: "http://localhost:3000/assets/types/water.png",
        imgUrlOutline: "http://localhost:3000/assets/types/waterOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Electric",
        color: "0xFFF4D23C",
        imgUrl: "http://localhost:3000/assets/types/electric.png",
        imgUrlOutline: "http://localhost:3000/assets/types/electricOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Grass",
        color: "0xFF63BC5A",
        imgUrl: "http://localhost:3000/assets/types/grass.png",
        imgUrlOutline: "http://localhost:3000/assets/types/grassOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ice",
        color: "0xFF73CEC0",
        imgUrl: "http://localhost:3000/assets/types/ice.png",
        imgUrlOutline: "http://localhost:3000/assets/types/iceOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fighting",
        color: "0xFFCE416B",
        imgUrl: "http://localhost:3000/assets/types/fighting.png",
        imgUrlOutline: "http://localhost:3000/assets/types/fightingOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Poison",
        color: "0xFFB567CE",
        imgUrl: "http://localhost:3000/assets/types/poison.png",
        imgUrlOutline: "http://localhost:3000/assets/types/poisonOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ground",
        color: "0xFFD97845",
        imgUrl: "http://localhost:3000/assets/types/ground.png",
        imgUrlOutline: "http://localhost:3000/assets/types/groundOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Flying",
        color: "0xFF89AAE3",
        imgUrl: "http://localhost:3000/assets/types/flying.png",
        imgUrlOutline: "http://localhost:3000/assets/types/flyingOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Psychic",
        color: "0xFFFA7179",
        imgUrl: "http://localhost:3000/assets/types/psychic.png",
        imgUrlOutline: "http://localhost:3000/assets/types/psychicOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bug",
        color: "0xFF91C12F",
        imgUrl: "http://localhost:3000/assets/types/bug.png",
        imgUrlOutline: "http://localhost:3000/assets/types/bugOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rock",
        color: "0xFFC5B78C",
        imgUrl: "http://localhost:3000/assets/types/rock.png",
        imgUrlOutline: "http://localhost:3000/assets/types/rockOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ghost",
        color: "0xFF5269AD",
        imgUrl: "http://localhost:3000/assets/types/ghost.png",
        imgUrlOutline: "http://localhost:3000/assets/types/ghostOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dragon",
        color: "0xFF0B6DC3",
        imgUrl: "http://localhost:3000/assets/types/dragon.png",
        imgUrlOutline: "http://localhost:3000/assets/types/dragonOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dark",
        color: "0xFF5A5465",
        imgUrl: "http://localhost:3000/assets/types/dark.png",
        imgUrlOutline: "http://localhost:3000/assets/types/darkOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Steel",
        color: "0xFF5A8EA2",
        imgUrl: "http://localhost:3000/assets/types/steel.png",
        imgUrlOutline: "http://localhost:3000/assets/types/steelOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fairy",
        color: "0xFFEC8FE6",
        imgUrl: "http://localhost:3000/assets/types/fairy.png",
        imgUrlOutline: "http://localhost:3000/assets/types/fairyOutline.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Types", null, {});
  },
};
