name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Set the working directory to the Pokedex/frontend folder
      - name: Install dependencies
        run: dart pub get
        working-directory: frontend  # Correct directory path here

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      #   working-directory: Pokedex/frontend

      - name: Analyze project source
        run: flutter analyze
        working-directory: frontend

      - name: Run tests
        run: flutter test
        working-directory: frontend
