name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Set up Flutter (not Dart)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
     

      # ✅ Install dependencies using Flutter
      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      # ✅ Analyze code
      - name: Analyze project source
        run: flutter analyze
        working-directory: frontend

      # ✅ Run Flutter tests
      - name: Run tests
        run: flutter test
        working-directory: frontend
